#!/usr/bin/env bash
# Idempotent repository bootstrap for the conscRAG (STEM RAG) platform.
#
# Prepares a fully local development stack that needs no external API keys:
#   * Python venv + backend dependencies (FastAPI, Qdrant client, ...)
#   * CPU-only PyTorch + sentence-transformers for LOCAL embeddings
#   * A local Qdrant server binary (no Docker required)
#   * Ingests the bundled seed + premium knowledge into Qdrant (one time)
#   * Frontend (Next.js) dependencies
#
# Adding DEEPSEEK_API_KEY (and optionally OPENAI_API_KEY / Supabase) as secrets
# unlocks the full multi-agent answer flow; retrieval works without any keys.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/env.sh"

cd "$REPO_ROOT"
mkdir -p "$STEM_RAG_HOME" "$QDRANT_DIR" "$HF_HOME" "$(dirname "$BM25_INDEX_ABS")"

# ---------------------------------------------------------------------------
# 0. System package: python venv support (ensurepip) if missing
# ---------------------------------------------------------------------------
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  log "Installing python3-venv (ensurepip) via apt"
  py_minor="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
  sudo apt-get update -qq
  sudo apt-get install -y -qq "python${py_minor}-venv" || sudo apt-get install -y -qq python3-venv
fi

# ---------------------------------------------------------------------------
# 1. Local Qdrant server binary
# ---------------------------------------------------------------------------
if [[ ! -x "$QDRANT_BIN" ]]; then
  log "Downloading Qdrant ${QDRANT_VERSION} server binary"
  tarball="$QDRANT_DIR/qdrant.tar.gz"
  url="https://github.com/qdrant/qdrant/releases/download/v${QDRANT_VERSION}/qdrant-x86_64-unknown-linux-gnu.tar.gz"
  curl -fsSL "$url" -o "$tarball"
  tar -xzf "$tarball" -C "$QDRANT_DIR"
  rm -f "$tarball"
  chmod +x "$QDRANT_BIN"
  log "Qdrant binary installed at $QDRANT_BIN"
else
  log "Qdrant binary already present ($("$QDRANT_BIN" --version 2>/dev/null | head -1 || echo present))"
fi

# ---------------------------------------------------------------------------
# 2. Python virtual environment + backend dependencies
# ---------------------------------------------------------------------------
if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  log "Creating Python virtual environment at $VENV_DIR"
  python3 -m venv "$VENV_DIR"
fi
# shellcheck source=/dev/null
source "$VENV_DIR/bin/activate"

log "Installing backend dependencies"
python -m pip install --upgrade pip >/dev/null
pip install -r "$REPO_ROOT/backend/requirements.txt"

# CPU-only PyTorch (avoids the large CUDA wheels) + sentence-transformers so the
# app can run the LOCAL embedding provider with no OpenAI/Voyage key.
log "Installing CPU PyTorch + sentence-transformers (local embeddings)"
pip install --index-url https://download.pytorch.org/whl/cpu "torch>=2.2,<2.9"
pip install "sentence-transformers>=3.3.0"

# ---------------------------------------------------------------------------
# 3. Backend .env (local, key-free defaults) — never overwrite an existing file
# ---------------------------------------------------------------------------
if [[ ! -f "$REPO_ROOT/backend/.env" ]]; then
  log "Writing backend/.env with local (no-API-key) defaults"
  cat >"$REPO_ROOT/backend/.env" <<EOF
# Auto-generated by .cursor/install.sh for local development.
# Local Qdrant server (started by .cursor/start.sh)
QDRANT_URL=${QDRANT_URL}
QDRANT_API_KEY=
COLLECTION_NAME=stem_vectors

# Local embeddings — no external API key required.
EMBEDDING_PROVIDER=local
EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
EMBEDDING_DIMENSIONS=384
EMBEDDING_QUERY_PREFIX=true
WARM_EMBEDDING_ON_STARTUP=false

# Multi-agent answers require a DeepSeek key. Retrieval works without it.
# Add DEEPSEEK_API_KEY via Cloud Agent secrets to enable full /api/query answers.
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}

# Supabase is optional (used only for the community "posts" portfolio).
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}

# Hybrid retrieval (dense + BM25). Absolute path keeps the generated index in
# durable storage instead of dirtying the repo's committed data/index copy.
HYBRID_SEARCH_ENABLED=true
BM25_INDEX_PATH=${BM25_INDEX_ABS}

# CORS for the local Next.js dev server
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
CORS_ORIGIN_REGEX=

ADMIN_API_KEY=local-dev-admin-key
EOF
else
  log "backend/.env already exists — leaving it untouched"
fi

# ---------------------------------------------------------------------------
# 4. Pre-download the local embedding model (bakes into the snapshot cache)
# ---------------------------------------------------------------------------
log "Pre-downloading local embedding model into $HF_HOME"
python - <<'PY'
import os
from sentence_transformers import SentenceTransformer
model = os.environ.get("STEM_EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5")
SentenceTransformer(model, device="cpu")
print(f"Model ready: {model}")
PY

# ---------------------------------------------------------------------------
# 5. Ingest bundled knowledge into Qdrant (one-time; skipped if already present)
# ---------------------------------------------------------------------------
start_qdrant
collection="$(grep -E '^COLLECTION_NAME=' "$REPO_ROOT/backend/.env" | cut -d= -f2)"
collection="${collection:-stem_vectors}"
points="$(curl -fsS "${QDRANT_URL}/collections/${collection}" 2>/dev/null \
  | python3 -c 'import sys,json;
try:
    d=json.load(sys.stdin); print(d.get("result",{}).get("points_count") or 0)
except Exception:
    print(0)' 2>/dev/null || echo 0)"

if [[ "${points:-0}" -gt 0 && -f "$BM25_INDEX_ABS" ]]; then
  log "Qdrant collection '${collection}' already populated (${points} points) and BM25 index present — skipping ingest"
elif [[ "${points:-0}" -gt 0 ]]; then
  log "Qdrant populated (${points} points) but BM25 index missing — rebuilding BM25 from Qdrant"
  ( cd "$REPO_ROOT/backend" && python scripts/ingest_premium.py --rebuild-bm25 )
else
  log "Ingesting seed + premium knowledge into Qdrant (this runs the local embedder)"
  ( cd "$REPO_ROOT/backend" && python scripts/ingest_premium.py --fresh )
fi

# ---------------------------------------------------------------------------
# 6. Frontend dependencies + local env
# ---------------------------------------------------------------------------
if [[ ! -f "$REPO_ROOT/frontend/.env.local" ]]; then
  log "Writing frontend/.env.local"
  echo "NEXT_PUBLIC_API_URL=http://localhost:8000" >"$REPO_ROOT/frontend/.env.local"
fi

log "Installing frontend dependencies (npm ci)"
( cd "$REPO_ROOT/frontend" && npm ci )

log "Install complete. Start services with .cursor/start.sh (Qdrant) + the backend/frontend terminals."
